name: CI/CD

on:
  push:
    branches: [ master ]

jobs:
  my-job:
    name: CI/CD Job
    runs-on: ubuntu-latest
    steps:

      - name: Checkout master branch
        uses: actions/checkout@v2

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@1.16
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}